--Weather Observation Station 5
SELECT CITY, LENGTH(CITY) L FROM STATION
ORDER BY L DESC, CITY
LIMIT 1;
SELECT CITY, LENGTH(CITY) L FROM STATION
ORDER BY L ASC, CITY
LIMIT 1;

--Weather Observation Station 2
SELECT ROUND(SUM(LAT_N), 2), ROUND(SUM(LONG_W), 2)
FROM STATION;
